version: "3.8"

services:
  wp:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - wp_files:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins:Z
      - ./themes:/var/www/html/wp-content/themes:Z
      - ./uploads:/var/www/html/wp-content/uploads:Z
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    restart: unless-stopped

  db:
    image: mariadb:latest
    volumes:
      - shop_db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  wpcli:
    image: wordpress:cli
    user: '33'
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wp_files:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins:Z
      - ./themes:/var/www/html/wp-content/themes:Z
      - ./uploads:/var/www/html/wp-content/uploads:Z
    command: >
      /bin/sh -c "
      sleep 15;
      wp core install --path=/var/www/html --url=http://localhost:8080 --title=\"Local Wordpress By Podman\" \
        --admin_user=${WP_ADMIN_USER} --admin_password=${WP_ADMIN_PASSWORD} --admin_email=${WP_ADMIN_EMAIL};
      wp plugin install woocommerce --activate;
      wp theme install blocksy --activate; "

volumes:
  shop_db: {}
  wp_files: {}
